region: ap-northeast-1
cluster: readable-coder-prod
service: readable-coder-prod
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: "10m0s"
plugins:
  - name: tfstate
    config:
      url: s3://readable-coder-tfstate/prod/cicd.tfstate